AllCops:
  Exclude:
    - app/views/**/*
    - coverage/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*

Bundler/OrderedGems:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 50
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - config/routes_api.rb
    - db/migrate/*
    - db/schema.rb
    - spec/**/*.rb

Metrics/LineLength:
  Max: 120
  Exclude:
    - config/initializers/devise.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*

Metrics/ParameterLists:
  Max: 10

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/**/*