openapi: 3.0.0

info:
  version: 0.0.0
  title: Todo API

servers:
  - url: http://localhost:3000
    description: Local

tags:
  - name: users
  - name: tasks

paths:
  /api/v1/me:
    get:
      tags:
        - users
      summary: ログインユーザー情報を取得
      security:
        - oauth2
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
  /api/v1/tasks:
    get:
      tags:
        - tasks
      summary: タスク一覧を取得
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - tasks
      summary: タスクを登録
      requestBody:
        content:
          application/x-www-form-urulencoded:
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        201:
          $ref: "#/components/responses/201"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
  /api/v1/tasks/{id}:
    get:
      tags:
        - tasks
      summary: タスクを取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        401:
          $ref: "#/components/responses/401"
        500:
          $ref: "#/components/responses/500"
    patch:
      tags:
        - tasks
      summary: タスクを更新
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/x-www-form-urulencoded:
            schema:
              $ref: "#/components/schemas/TaskForm"
    delete:
      tags:
        - tasks
      summary: タスクを削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number

components:
  responses:
    200:
      description: OK
    201:
      description: Created
    204:
      description: No Content
    400:
      description: Bad Request
    401:
      description: Unauthorized
    402:
      description: Payment Required
    403:
      description: Forbidden
    404:
      description: Not Found
    500:
      description: Internal Server Error
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /auth/oauth/authorize
          tokenUrl: /auth/oauth/token
          refreshUrl: /auth/oauth/token
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
          nullable: false
        email:
          type: string
          nullable: false
        created_at:
          type: string
          format: date-time
          nullable: false
        updated_at:
          type: string
          format: date-time
          nullable: false
    Task:
      type: object
      properties:
        id:
          type: number
          nullable: false
        title:
          type: string
          nullable: false
        description:
          type: string
          nullable: true
        done:
          type: boolean
          nullable: false
        created_at:
          type: string
          format: date-time
          nullable: false
        updated_at:
          type: string
          format: date-time
          nullable: false
    TaskForm:
      type: object
      properties:
        title:
          type: string
          nullable: false
        description:
          type: string
          nullable: true
        done:
          type: boolean
          nullable: false
